name: Frontend cicd

on: 
  push:
    branches:
      - test
    # paths:
    #   - "frontend/**"

jobs:
  frontend:
    runs-on: ubuntu-latest
    

    steps:
        - uses: actions/checkout@v3
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        
        - name: docker build tag and push to AWS ECR
          run: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 783490811281.dkr.ecr.us-east-1.amazonaws.com
            docker build -t frontend:v1 ./frontend
            docker tag frontend:v1 783490811281.dkr.ecr.us-east-1.amazonaws.com/frontend:v1
            docker push 783490811281.dkr.ecr.us-east-1.amazonaws.com/frontend:v1
        
        - name: deploy to AWS EC2 instance
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 783490811281.dkr.ecr.us-east-1.amazonaws.com
              cd /home/ubuntu
              docker pull 783490811281.dkr.ecr.us-east-1.amazonaws.com/frontend:v1
              docker rm -rf frontend || true
              docker run -d -p 80:80 --name frontend 783490811281.dkr.ecr.us-east-1.amazonaws.com/frontend:v1
              