name: Backend cicd
on:
  push:
    paths:
      - "backend/**"

jobs: 
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: login to ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: docker build tag and push to AWS ECR
      run: |
        docker build -t backend:v1 ./backend
        docker tag backend:v1 123456789012.dkr.ecr.us-east-1.amazonaws.com/backend:v1
        docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/backend:v1

    - name: deploy to AWS EC2 instance using ssm
      uses: aws-actions/amazon-ssm-run-command@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
        document-name: AWS-RunShellScript
        parameters: commands="cd /home/ubuntu/backend && docker image prune -f && docker compose down || true && docker compose pull && docker compose up -d"